version: '3.8'
services:
  auth:
    build:
      context: ./packages/auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=supersecret
  orchestrator:
    build:
      context: ./packages/orchestrator
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth
  anonymous-agent:
    build:
      context: ./packages/agents/anonymous-agent
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - orchestrator
  dashboard:
    build:
      context: ./apps/dashboard
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - orchestrator
