name: Deploy Rocket Fuell Girls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Test app start
      run: |
        timeout 10s npm start || true
        echo "App startup test completed"
    
    - name: Check for security vulnerabilities
      run: npm audit --audit-level moderate

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t rocket-fuell-girls .
    
    - name: Test Docker container
      run: |
        docker run -d -p 3000:3000 --name test-app rocket-fuell-girls
        sleep 10
        curl -f http://localhost:3000/api/health || exit 1
        docker stop test-app

  deploy:
    runs-on: ubuntu-latest
    needs: [test, docker-build]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    # Example deployment to a VPS (uncomment and configure as needed)
    # - name: Deploy to VPS
    #   uses: appleboy/ssh-action@v0.1.5
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY }}
    #     script: |
    #       cd /path/to/rocket-fuell-girls
    #       git pull origin main
    #       docker-compose down
    #       docker-compose up -d --build
    
    - name: Deployment success
      run: echo "🚀 Rocket Fuell Girls deployed successfully!"