name: MIGI-CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend requirements (if present)
        run: |
          if [ -f backend/requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r backend/requirements.txt
          else
            echo "No backend requirements.txt found, skipping"
          fi
      - name: Run backend tests (pytest)
        working-directory: backend
        run: |
          if [ -f pytest.ini ] || [ -d tests ] || [ -f requirements.txt ]; then
            pytest -q || (echo "Pytests failed"; exit 1)
          else
            echo "No tests detected under backend"
          fi

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend deps
        working-directory: frontend
        run: |
          if [ -f frontend/package.json ]; then
            npm ci
            npm run build --if-present
          else
            echo "No frontend detected"
          fi

  manifest-check:
    runs-on: ubuntu-latest
    needs: [ backend-tests, frontend-build ]
    steps:
      - uses: actions/checkout@v4
      - name: Verify migi_manifest.json presence
        run: |
          if [ ! -f migi_manifest.json ]; then
            echo "migi_manifest.json missing" && exit 1
          fi
      - name: Basic manifest validation (python)
        run: |
          python - <<'PY'
import json,sys
try:
  m = json.load(open('migi_manifest.json','r'))
  for k in ['name','version','commit_hash','modules','transmissions']:
    assert k in m
  assert isinstance(m['transmissions'], list)
  print("manifest ok")
except Exception as e:
  print("manifest validation failed:", e)
  sys.exit(1)
PY